mysql:
  host: 127.0.0.1
  port: 3306
  user: root
  password: 123456
  db: srbac
  charset: utf8mb4
redis:
  host: 127.0.0.1
  port: 6379
  password:
  db: 0
session:
  key: 19be30e8a9850e5cb5d1f7e3e47bde35